### ISSUE TITLE
Potential Issue: COMACN not reading encrypted web.config

### ISSUE THREAD

**Issue by BasesJs** [rlwakefield/CoMaCon#85]
**Describe the bug**
I get an error trying to open the web.config:
The following error(s) happened when loading your Web Application:
Error getting the string to send to COMACON Helper Utility. See the log file for more details.

The Web.config was encrypted NOT by the the WAMCON,but by the following code:

string nodeName = "/configuration/connectionStrings";
nodeName = xPath.Split('/').Last();
var aspNetRegIISPath = (string)Microsoft.Win32.Registry.GetValue("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full", "InstallPath", null);
using (var process = new Process())
{
    process.StartInfo.FileName = Path.Combine(aspNetRegIISPath, "aspnet_regiis.exe");
    process.StartInfo.Arguments = $"-pef {nodeName} \"{webConfig.DirectoryName}\" -prov DpapiProvider";
    process.StartInfo.CreateNoWindow = true;
    process.StartInfo.UseShellExecute = false;
    process.Start();
    process.WaitForExit();
}

The web.config opens in WAMCON, so my assumption was that I was encrypting correctly. Curious to see what you might find out.

**Comment by BasesJs** [comment]
[web.txt](https://github.com/user-attachments/files/16839791/web.txt)

**Comment by BasesJs** [comment]
finally, output from your log:
2024-09-02 12:21:44.372 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.402 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.402 -04:00 [WRN] Error parsing the WorkViewApi node path for the url attribute in the Hyland.ResponsiveApps section.
2024-09-02 12:21:44.402 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.403 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.404 -04:00 [WRN] Error parsing the WorkViewFiles node path for the url attribute in the Hyland.ResponsiveApps section.
2024-09-02 12:21:44.404 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.404 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.404 -04:00 [WRN] Error parsing the ResponsiveAppsApi node path for the url attribute in the Hyland.ResponsiveApps section.
2024-09-02 12:21:44.405 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.405 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.405 -04:00 [WRN] Error parsing the IdentityProvider node path for the url attribute in the Hyland.ResponsiveApps section.
2024-09-02 12:21:44.406 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.406 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.406 -04:00 [WRN] Error parsing the UnityEditableFilterMaxRows node path for the value attribute in the Hyland.WorkView.Core section.
2024-09-02 12:21:44.406 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.406 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseSpecificKeys(webApplicationWebConfigConfiguration ds, XmlNode node, String sect) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 2004
2024-09-02 12:21:44.406 -04:00 [WRN] Error parsing the ERPDateFormat node path for the value attribute in the Hyland.WorkView.Core section.
2024-09-02 12:21:44.406 -04:00 [WRN] Object reference not set to an instance of an object.
2024-09-02 12:21:44.406 -04:00 [WRN]    at COMACON.config.DefaultGenericHelperMethods.ParseWorkViewCoreFormattedTextIframeSupportedDomains(webApplicationWebConfigConfiguration ds, XmlNode node) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 1267
2024-09-02 12:21:44.406 -04:00 [WRN] Error parsing FormattedTextIframeSupportedDomains.
2024-09-02 12:21:46.348 -04:00 [ERR] Error: The parameter is incorrect.
2024-09-02 12:21:46.349 -04:00 [ERR] Error:    at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optionalEntropy, DataProtectionScope scope, Boolean protect)
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at COMACON.config.DefaultGenericHelperMethods.processTranslator(ComaconHelperProxy ComaconHelperProxy, String webApplicationType, String webApplicationVersion, String applicationName, String applicationPath, XmlNode root, webApplicationWebConfigConfiguration webconfigconfig, Configuration config, XmlDocument xmlDoc, WebApplicationDataStructures webApplicationDataStructures) in C:\Users\HP\source\repos\COMACON\CoMaCon\COMACON\config\GenericHelperMethods.cs:line 1140
2024-09-02 12:21:46.349 -04:00 [ERR] Version: 241
2024-09-02 12:21:46.349 -04:00 [ERR] Type: Application Server
